### ISSUE TITLE
Euler angles Range

### ISSUE THREAD

**Issue by veeresh-dammur** [thecountoftuscany/PyTeapot-Quaternion-Euler-cube-rotation#6]
Hi, 
Thanks for the nice repo. I would like to ask about the Euler angle ranges obtained from MPU9250. Do you get the orientation values between -180 to +180 degrees on each Euler axes (yaw, roll, pitch)?

**Comment by thecountoftuscany** [comment]
Please refer `quat_to_ypr()` function in `pyteapot.py`. Yaw and roll angles are obtained with the `math.atan2()` function, which returns angles in [-pi, pi]. Pitch is obtained with `math.asin()`, which returns angles in [-pi/2, pi/2] (refer [this page](https://docs.python.org/3/library/math.html))

**Comment by thecountoftuscany** [comment]
Also note that, as mentioned in the readme, this repo assumes that orientation data has been calculated already (for example, using [this code](https://github.com/kriswiner/MPU9250/blob/master/quaternionFilters.ino)) and is only concerned with visualizing that orientation. In case your algorithm calculates quaternions, this repo contains a function that converts that to yaw, pitch, roll angles as mentioned in my previous response. In case it provides yaw, pitch, roll angles, the sensor fusion implementation used defines the ranges.

**Comment by veeresh-dammur** [comment]
Just off the topic of the created issue, Currently, we are using BNO055 in one of our projects. The IMU is placed next to the dc motor due to space constraints within the hardware setup. Due to motors vibrations, we are applying a low pass filter on quaternion values read from [this](https://github.com/adafruit/Adafruit_BNO055/blob/master/examples/rawdata/rawdata.ino) script. We have set 5 Hz as a cut-off frequency of the filter. We have also placed IMU on Sorbothane (damping material) to minimize the vibrations. However, we are still selling the error in the orientation.

What could be done to reduce the impact of motor vibrations on IMU both from a software and hardware point of view? Any inputs are highly appreciated!

**Comment by thecountoftuscany** [comment]
Apart from what you have already mentioned, I can only think of a few things:
- Try to apply filters on the raw accelerometer and/or gyroscope measurements and then apply sensor fusion instead of applying filters on the quaternions fused from noisy measurements since that is a highly non-linear operation. I don't know if the particular IMU you are working with has a library that lets you readily do this, although the datasheet _should_ help you implement this on your own using standard libraries (eg. you should be able to find libraries for TWI (aka I2C), SPI, or whatever interface that IMU uses)
- Maybe also try to characterize the motor vibration frequency(ies?) and set the cut off frequency for your filter accordingly?
- (Digital) Signal Processing is a huge domain in itself: try to find a better filter for this particular use case. However, this is not my area of expertise and hence cannot recommend something for this
- Read up on standard methods for vibration isolation. The wikipedia [page](https://en.wikipedia.org/wiki/Vibration_isolation) could be a start. You can find some good review papers on the topic too.
Also it depends on what you mean by "error in orientation". In general, IMUs (ones based on accel+mag+gyro) tend to drift. You can increase accuracy or reduce drift by using better sensors (or better sensor fusion techniques) but in the end, this is unavoidable without fusing with additional sensors. Try to figure out if the problem you are referring to is indeed because of the vibration (eg, look at orientation without keeping it close to the motor). That's all I can say for now.
